// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWsSwitchingProtocolsCode is the HTTP code returned for type GetWsSwitchingProtocols
const GetWsSwitchingProtocolsCode int = 101

/*GetWsSwitchingProtocols Done

swagger:response getWsSwitchingProtocols
*/
type GetWsSwitchingProtocols struct {
}

// NewGetWsSwitchingProtocols creates GetWsSwitchingProtocols with default headers values
func NewGetWsSwitchingProtocols() *GetWsSwitchingProtocols {

	return &GetWsSwitchingProtocols{}
}

// WriteResponse to the client
func (o *GetWsSwitchingProtocols) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(101)
}
