// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetWsReader is a Reader for the GetWs structure.
type GetWsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 101:
		result := NewGetWsSwitchingProtocols()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWsSwitchingProtocols creates a GetWsSwitchingProtocols with default headers values
func NewGetWsSwitchingProtocols() *GetWsSwitchingProtocols {
	return &GetWsSwitchingProtocols{}
}

/*GetWsSwitchingProtocols handles this case with default header values.

Done
*/
type GetWsSwitchingProtocols struct {
}

func (o *GetWsSwitchingProtocols) Error() string {
	return fmt.Sprintf("[GET /ws][%d] getWsSwitchingProtocols ", 101)
}

func (o *GetWsSwitchingProtocols) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
