// Code generated by go-swagger; DO NOT EDIT.

package weather_assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"senior-software-engineer-takehome/models"
)

// NewPostDataWeatherParams creates a new PostDataWeatherParams object
// with the default values initialized.
func NewPostDataWeatherParams() *PostDataWeatherParams {
	var ()
	return &PostDataWeatherParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDataWeatherParamsWithTimeout creates a new PostDataWeatherParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDataWeatherParamsWithTimeout(timeout time.Duration) *PostDataWeatherParams {
	var ()
	return &PostDataWeatherParams{

		timeout: timeout,
	}
}

// NewPostDataWeatherParamsWithContext creates a new PostDataWeatherParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDataWeatherParamsWithContext(ctx context.Context) *PostDataWeatherParams {
	var ()
	return &PostDataWeatherParams{

		Context: ctx,
	}
}

// NewPostDataWeatherParamsWithHTTPClient creates a new PostDataWeatherParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDataWeatherParamsWithHTTPClient(client *http.Client) *PostDataWeatherParams {
	var ()
	return &PostDataWeatherParams{
		HTTPClient: client,
	}
}

/*PostDataWeatherParams contains all the parameters to send to the API endpoint
for the post data weather operation typically these are written to a http.Request
*/
type PostDataWeatherParams struct {

	/*Body*/
	Body *models.WeatherUnit

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post data weather params
func (o *PostDataWeatherParams) WithTimeout(timeout time.Duration) *PostDataWeatherParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post data weather params
func (o *PostDataWeatherParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post data weather params
func (o *PostDataWeatherParams) WithContext(ctx context.Context) *PostDataWeatherParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post data weather params
func (o *PostDataWeatherParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post data weather params
func (o *PostDataWeatherParams) WithHTTPClient(client *http.Client) *PostDataWeatherParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post data weather params
func (o *PostDataWeatherParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post data weather params
func (o *PostDataWeatherParams) WithBody(body *models.WeatherUnit) *PostDataWeatherParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post data weather params
func (o *PostDataWeatherParams) SetBody(body *models.WeatherUnit) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDataWeatherParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
