// Code generated by go-swagger; DO NOT EDIT.

package weather_assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDataWeatherHandlerFunc turns a function with the right signature into a post data weather handler
type PostDataWeatherHandlerFunc func(PostDataWeatherParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDataWeatherHandlerFunc) Handle(params PostDataWeatherParams) middleware.Responder {
	return fn(params)
}

// PostDataWeatherHandler interface for that can handle valid post data weather params
type PostDataWeatherHandler interface {
	Handle(PostDataWeatherParams) middleware.Responder
}

// NewPostDataWeather creates a new http.Handler for the post data weather operation
func NewPostDataWeather(ctx *middleware.Context, handler PostDataWeatherHandler) *PostDataWeather {
	return &PostDataWeather{Context: ctx, Handler: handler}
}

/*PostDataWeather swagger:route POST /data/weather Weather Assets postDataWeather

Single weather data is created

*/
type PostDataWeather struct {
	Context *middleware.Context
	Handler PostDataWeatherHandler
}

func (o *PostDataWeather) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostDataWeatherParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
